name: C/C++ CI

on:
  push:
    branches: [ anclarma_dev, lzaccome, main ]
  pull_request:
    branches: [ anclarma_dev, lzaccome, main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        if [ "$RUNNER_OS" == "macOS" ]
        then
            brew install readline
        fi
        make
    - name: make check
      run: make check
    - name: norminette
      run: |
        pip3 install norminette
        norminette
